### ISSUE TITLE
--silent seems bugged, with json format

### ISSUE THREAD

**Issue by twk-b** [JustinBeckwith/linkinator#117]
```json
{
  "format": "json",
  "recurse": true,
  "silent": true,
  "concurrency": 100,
  "skip": "www.googleapis.com"
}
```

* `linkinator URL``` all results still returned
* `linkinator --silent URL``` all results still returned

format=csv seems to work

**Comment by JustinBeckwith** [comment]
Greetings!  With the `1.7.4` release, this appears to work as expected.  If it's not - could you provide the exact command you're running, and the exact output?

**Comment by JustinBeckwith** [comment]
Going to go ahead and close this out for now.  If you're still running into issues - please do let me know!

**Comment by twk-b** [comment]
```json
{
  "format": "json",
  "recurse": true,
  "silent": true,
  "concurrency": 100,
  "skip": "www.googleapis.com"
}
```
cmd: linkinator --version
1.8.0

cmd: linkinator --silent https://mywebsite.com/

output still includes:
    {
      "url": "https://mywebsite.com/wiki",
      "status": 200,
      "state": "OK",
      "parent": "https://mywebsite.com/wiki"
    }

expecting no STATUS = 200

**Comment by twk-b** [comment]
1.8.2 retested, problem still exists.... with silent in config on command line also still fails.

**Comment by twk-b** [comment]
```diff cli.js node_modules/linkinator/build/src/cli.js
4d3
< const _ = require('lodash');
117,119d114
<         if (flags.silent) {
<             result.links = _.reject(result.links, { state: 'OK' })
<         }
```

**Comment by pjoulot** [comment]
Are you using silent as an option in the check method? Silent is only supported if you are using the cli.

CheckOptions doesn't support silent:
```
export interface CheckOptions {
    concurrency?: number;
    port?: number;
    path: string;
    recurse?: boolean;
    linksToSkip?: string[] | ((link: string) => Promise<boolean>);
}
```

**Comment by twk-b** [comment]
running it from the command line, with --silent passed, and either cli param and/or config for JSON output, the JSON output still has valid links (status 200, state skipped)
