### ISSUE TITLE
add support for an optional link filtering function

### ISSUE THREAD

**Issue by zeke** [JustinBeckwith/linkinator#119]
Hi @JustinBeckwith and maintainers. This is a nice module! Thanks for writing it.

In the current API doc:

> `linksToSkip` (array) - An array of regular expression strings that should be skipped during the scan.

This works, but it can be cumbersome to write exclusion rules just using regular expressions. It would be nifty if this option (or a new option) could be passed a function instead of an array. The function would take the given link URL as input and return a Boolean indicating whether to skip it or not:

```js
filterLinks: (url) => {
  return true // or false
}
```

I'd be willing to open a PR to add support for this. Would you be open to this change?

**Comment by zeke** [comment]
I jumped the gun and opened a PR for this anyway: https://github.com/JustinBeckwith/linkinator/pull/120

**Comment by JustinBeckwith** [comment]
This sounds great, and thanks for the PR!  I left some feedback over there :)

**Comment by JustinBeckwith** [comment]
Thank you again for the PR!  This was fixed in #120 - the release should be coming out momentarily.
