### ISSUE TITLE
rel="preconnect" possible issue

### ISSUE THREAD

**Issue by Auo** [JustinBeckwith/linkinator#133]
```
<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="">
```
will result in
```
[404] https://fonts.gstatic.com/
```
The page itself does indeed return `404` but the following requests for fonts will succeed,
e.g. https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2

Maybe `preconnect` should just check that it could contact the server, but ignore the response code?

**Comment by Trott** [comment]
Same for `dns-prefetch`.

**Comment by JustinBeckwith** [comment]
As a workaround before we get to fixing this:  for now, you can include the URI in question in your skipped links in the config, so it doesn't break CI :)
