### ISSUE TITLE
config {skip: 'string'} needs to be config { skip: ['strings'] }

### ISSUE THREAD

**Issue by twk-b** [JustinBeckwith/linkinator#137]
config {skip: 'string'} needs to be config { skip: ['strings'] }

lots of things need to be added to stay out of trouble with various resources, a single regex doesnt make that easy. should allow an array of either domains, or regex

**Comment by JustinBeckwith** [comment]
You can totally do that!  You can pass `--skip` multiple times from the command line:

```
$ linkinator https://googleapis.dev/nodejs/bigquery/latest/ --skip github.com --skip cloud.google.com
```

You can also set this via the config:

```json
{
  "recurse": true,
  "skip": [
    "https://codecov.io/gh/googleapis/",
    "www.googleapis.com",
    "img.shields.io"
  ]
}
```

Hope this helps!

**Comment by djibe** [comment]
Hi,
in latest linkinator cli, when sending --skip recomedicales.fr --skip github.com

We get `Error: The flag --skip can only be set once`.

**Comment by JustinBeckwith** [comment]
@djibe please open a new issue with details!
