### ISSUE TITLE
[Feature Request] Add request timeout option

### ISSUE THREAD

**Issue by romainwurtz** [JustinBeckwith/linkinator#161]
It would be great to have a timeout option as "gaxios" does not currently have one by default and potentially could hang the crawling process. The timeout could be set to 60 sec by default just in case.

We had the issue with an external link never returning anything and adding this option fixed it on our end.

**Comment by pjoulot** [comment]
By any chance, do you have a patch? Or tell me which line you changed? I have the same problem, the problem is stuck sometimes. Thank you.

**Comment by pjoulot** [comment]
Actually I found out that my process was getting stuck  by the concurrency flag. If I reduce the default (100) to 1, the execution finish without being stuck but if I leave the minimum, it just never end...

**Comment by JustinBeckwith** [comment]
Yeah - the concurrency thing is super annoying, because the number of concurrent requests nodejs can handle before returning errors is wildly dependent on the machine specs where the test is being run.  We had to turn it way down for GitHub actions to work properly.
