### ISSUE TITLE
[Enhancement Idea] only show path in CLI output when scanning locally

### ISSUE THREAD

**Issue by nkuehn** [JustinBeckwith/linkinator#166]
Hi, I happily discovered linkinator as a better maintained CLI for broken link checking.   

I'll likely switch to using it in any case but nevertheless here's one thing that the (not as technical) content authors that have to handle the broken links output would appreciate:

If the linkinator is scanning a local directory with a local webserver  the CLI output would make more sense to users if the `https://localhost:0000/` part of both the page the broken link was found on and the broken link target were removed.

**Comment by JustinBeckwith** [comment]
Hey this is a great idea!  I'm curious - do you think relative URL paths would be good, or do you think it would be better to translate this back into the local file path?  For instance this:

```
[200] http://localhost:5259/css/site.css
[200] http://localhost:5259/manifest.json
[200] http://localhost:5259/about/
[200] http://localhost:5259/2019/12/18/package-lock/
[200] http://localhost:5259/archive/
```

Could become this:

```
[200] /css/site.css
[200] /manifest.json
[200] /about/
[200] /2019/12/18/package-lock/
[200] /archive/
```

Or we could show the relative path to the file on the file system (I think I can do that...):

```
[200] ./css/site.css
[200] ./manifest.json
[200] ./about/index.html
[200] ./2019/12/18/package-lock/index.html
[200] ./archive/index.html
```

Or an absolute path to the file on the filesystem:

```
[200] /Users/beckwith/Code/mysite/css/site.css
[200] /Users/beckwith/Code/mysite/manifest.json
[200] /Users/beckwith/Code/mysite/about/index.html
[200] /Users/beckwith/Code/mysite/2019/12/18/package-lock/index.html
[200] /Users/beckwith/Code/mysite/archive/index.html
```

I do think you have a really good point, and at the very least I'm going to start with trimming the host from the path

**Comment by nkuehn** [comment]
My Idea was only based on making it simpler to read from the perspective of the person that authored the link in the site and then sees the output in the failed build's log.   From that perspective `/css/site.css`  makes most sense to me.  

I don't think the relative or absolute filesystem paths would be useful to me because I don't know a lot of scenarios any more where the HTML is authored by hand.  To fix a link the author needs to mentally map to the respective source file (or CMS) convention anyways.

**Comment by DavidAnson** [comment]
The option that makes the most sense to me is paths relative to the root of the scan:

```text
[200] css/site.css
[200] manifest.json
```

Starting with a slash feels technically wrong (that's an absolute path) and using an absolute path adds directories that aren't relevant to the user (Users, beckwith, etc.). The `./` option two comments above is second best in my mind: it's correct, but slightly more confusing as it requires the user to understand that syntax.
