### ISSUE TITLE
Does it have support for proxy to run within VPN network?

### ISSUE THREAD

**Issue by gauravgandhi1315** [JustinBeckwith/linkinator#195]

**Comment by gauravgandhi1315** [comment]
@JustinBeckwith Would you be able to help me here?

**Comment by gauravgandhi1315** [comment]
It works for me without VPN

**Comment by JustinBeckwith** [comment]
Sure, it should work fine.  Are you having any specific problems?

**Comment by gauravgandhi1315** [comment]
Yes, if i do `linkinator url` it doesn't show any broken URLs when I am connected to VPN. Without vpn, it does show all the `broken` and `OK` URLs.

**Comment by JustinBeckwith** [comment]
Just to make sure I understand - when you are connected to your VPN, all links come back as OK - even if requesting that url in your browser doesn't work?  What happens if you put one of these broken links in the browser?

**Comment by gauravgandhi1315** [comment]
@JustinBeckwith with VPN, I don’t get any results at all with any URL. Nothing come out as ok or broken. Without VPN, it works fine. Am I doing anything wrong? Or it doesn’t support VPN network

**Comment by JustinBeckwith** [comment]
Ah, that makes more sense.  The library should support proxies by setting the `HTTP_PROXY` or `HTTPS_PROXY` env vars.  That env var should point to the location of your proxy server.  In a unixy environment that would look like:
```
$ HTTP_PROXY=http://your-proxy:80 linkinator https://jbeckwith.com
```

Can you give something like that a shot?

**Comment by gauravgandhi1315** [comment]
@JustinBeckwith I tried this but it didn't work:

```
const result = await checker.check({
      HTTP_PROXY: new HttpProxyAgent('http://.......:80/'),
      path: "https://qwww.americanexpress.com/en-us/business/payment-solutions/employee-spending/
    });
```

**Comment by JustinBeckwith** [comment]
That is not at all what I described.  You need to set an environment variable.

**Comment by gauravgandhi1315** [comment]
Mac, I am running test through my script instead of command line.

**Comment by JustinBeckwith** [comment]
Yeah - there is no option to set a proxy via the API, only environment variable.  Whatever script you're running though - you can still pass env vars to it!  Is this a node.js program you're running?  You can set an env var in the same way I mentioned above:

```
$ HTTP_PROXY=http://your-proxy:80 node your-magical-script.js
```

**Comment by gauravgandhi1315** [comment]
@JustinBeckwith It works now. Thanks for your help. One qq - does it support array of URLs?

**Comment by JustinBeckwith** [comment]
Rad :) I added a blurb to the docs for the next person that comes along!  Next question - yes!  I think I just shipped this yesterday, but the `path` flag/option will accept either a string or an array of strings.  So you can pass in multiple URLs at once.

**Comment by gauravgandhi1315** [comment]
@JustinBeckwith I tried to run it with a 404 page like `https://www.npmjs.com/package/linkinator11` it still runs it without throwing error for the actual 404 which I have given. Any thoughts on this?

**Comment by JustinBeckwith** [comment]
If you do a curl against that URL using your proxy - what response code does it return?

**Comment by gauravgandhi1315** [comment]
@JustinBeckwith My question is more related to the functionality of the tool. Is it supposed to through error for the 404 url like I mentioned above `https://www.npmjs.com/package/linkinator11`. In my case, it didn't through error any url but instead it started checking the other sub URLs on the page.

**Comment by gauravgandhi1315** [comment]
@JustinBeckwith In my case, page has 404 - page not found but status code is 200.

**Comment by JustinBeckwith** [comment]
Yeah, in that case - there's nothing we can really do here :(. It sounds like the proxy server you're using is behaving badly, and linkinator can only really work at the HTTP layer to figure out what's happening.  I would suggest talking with your VPN provider about this one!
