### ISSUE TITLE
Suggestion: Add option to hide skipped files in console output

### ISSUE THREAD

**Issue by DavidAnson** [JustinBeckwith/linkinator#213]
When running via `'**/*.md' --markdown` and `--skip 'node_modules/'`, there are a LOT of skipped files in the console output. I don't care about any of them and they make it hard to see what good/bad links were checked. The `--silent` option hides good links which I don't want, either - it's nice to be able to confirm which links were checked. I would prefer not to see hundreds/thousands of skipped links - just the links that are being checked and their results. Thank you!

**Comment by JustinBeckwith** [comment]
Great suggestion.  This and #211 are kind of linked, and I think they would have the same solution.  Right now the only verbosity setting we have is `--silent`, but there are many things to pivot on:
- Do you show skipped links
- Do you show successfully scanned links
- Do you show the full call stack for failures 

There are probably more 🤷  Bouncing some ideas...  first thought is to go with a more traditional `verbosity` flag.  For example, stealing from `gcloud`:
```
 --verbosity=VERBOSITY; default="warning"
        Override the default verbosity for this command. Overrides the default
        core/verbosity property value for this command invocation. VERBOSITY
        must be one of: debug, info, warning, error, critical, none.
```
The break down could be like this:
- debug - show all the things all the time
- info - show skipped links, successfully scanned links, and failures.  Maybe don't show call stacks for failed links?
- warning - show successfully scanned links, and failures
- error - only show failures 
- none - not sure why anyone would want this, but suppress all output

Either way - I think the API should always return all the data, and leave the filtering as an exercise to the user.  

So @DavidAnson @case .. looking for thoughts!

**Comment by DavidAnson** [comment]
In your original proposal, `warning` is exactly what I want, so I'd be happy. :) I was about to suggest flags, but you beat me to it with your edit! That would be fine with me as well. Slightly more powerful, but more verbose as well. I think your hierarchy for the `--verbosity` flag is exactly right and probably pretty unarguable, so that may be safe enough.

**Comment by case** [comment]
Apologies for being a bit late in replying here (it's Xmas week :) ) -- I had in mind a verbosity option to show debug output for the failures, but keep the `--silent` functionality to hide the `200` successes.

e.g. currently I'm seeing a single failure out of ~200 successes, and when using `--verbosity debug` I still need to scroll through hundreds of `200` lines to find the single failure.

**Comment by JustinBeckwith** [comment]
Yeah - I mean at the stage where we're showing the the full error details, it's going to generate _a lot_ of output.  I wouldn't expect anyone to run with `--verbosity DEBUG` all the time, unless you're very rarely looking through the logs.  One of the things I'm figuring out - the exact way folks want the output to be formatted and filtered is going to change person to person, and I don't think there's one answer here that will make everyone happy.  As of now, I think I'm going to keep the verbosity settings the way they are.  

One of the reasons I'm doing that ...  you can pass the `--format JSON` flag, and then mutate the output in any way you like!  Check this out:

`linkinator https://gist.github.com/JustinBeckwith/8e3462b17dff040ac1a99435d66d1e2c --verbosity DEBUG --format JSON | jq '.links | .[] | select(.state | contains("BROKEN"))'`

Do you think this is going to get you where you want to go?
