### ISSUE TITLE
Investigate failures in twbs/bootstrap

### ISSUE THREAD

**Issue by JustinBeckwith** [JustinBeckwith/linkinator#233]
Starting with recentish release, linkinator started failing on a perfectly valid link in the bootstrap docs.  The issue was raised here:
https://github.com/twbs/bootstrap/pull/32678#issuecomment-754671269

This link shows a 404:
https://getbootstrap.com/docs/5.0/

I debugged a little and it turns out to be an issue with the https://github.com/vercel/serve-handler transition, which was done for directory listings.  More research needed. 

cc @XhmikosR

**Comment by XhmikosR** [comment]
Not sure if it will help, but after reading the source code a bit I think it'd be better if

1. this would be moved to a separate function https://github.com/JustinBeckwith/linkinator/blob/cb1d8082905eb04450ee74302cc6f7a7dc44680e/src/options.ts#L78-L107
2. perhaps use more `path` API methods in options.ts, like `basename`, `parse`, `join` etc instead of this manual handling of paths?

**Comment by XhmikosR** [comment]
In fact, it seem any directory with periods will return a 404 wrongfully.

See also my comment https://github.com/vercel/serve-handler/issues/139#issuecomment-766809449

Might be worth looking into something else :)

**Comment by JustinBeckwith** [comment]
Aye, apologies - been work busy.

**Comment by XhmikosR** [comment]
No worries, just trying to group all the info together.

**Comment by XhmikosR** [comment]
I want to also add something obvious that I was forgetting. On Windows, filenames cannot contain periods.

I hit this on another repo with linkinator 2.11.2, and I was like WTH.

But this original issue happens on nix.

**Comment by JustinBeckwith** [comment]
I started poking at this last night, and came to a funny conclusion ... I don't think I need an npm module for this at all.  Since we control both the server and the client, 90% of web server features aren't useful.  I started on a PR to replace this with a plain ol HTTP server.  More soon.
