### ISSUE TITLE
should linkinator parse non-html files?

### ISSUE THREAD

**Issue by callmehiphop** [JustinBeckwith/linkinator#30]
I imagine for the most part these would just yield 0 links since we search for links via cheerio's query selector. However it would appear we've stumbled onto an edge case where it finds links via JavaScript files with HTML stored as a string. This gets funky because link attributes end up getting double escaped `href=\"hi\"` -> `href=\\"hi\\"` at which point I believe the HTML parser assumes the quotes were simply omitted. 

I'm thinking we probably want to do one of the following

* Ignore non-HTML files
* Create an additional CLI flag to blacklist files or file types

WDYT?

**Comment by JustinBeckwith** [comment]
So this is a really good question.  Maybe we should only scan files that come back with a particular content type?  
- `Content-Type: text/html;`

**Comment by callmehiphop** [comment]
SGTM. I would think bad links embedded elsewhere are of little consequence unless they make it into the HTML as dynamic content.
