### ISSUE TITLE
Check broken anchor links

### ISSUE THREAD

**Issue by taylorreece** [JustinBeckwith/linkinator#305]
Thanks for the great tool!

I have a feature request: would it be possible to add functionality to check for broken anchor links? I have a docs site that cross-links between pages to specific portions of other pages, so I might `<a href="/docs/something#foo">`.  But, if I ever rename my heading on `something` from `foo` to `bar`, my anchor link breaks but the link is still seen as "valid" per linkinator. 

It'd be great when fed `<a href="/docs/something#foo">`, if linkinator could be configured to inspect `/docs/something` for an html element with property `id="foo"`.

Thanks a bunch!

**Comment by JustinBeckwith** [comment]
Greetings!  Can't do this quite yet, but agreed it would be nice to add.  We already have a feature request at https://github.com/JustinBeckwith/linkinator/issues/79, so I'm closing this in favor of the existing issue.
