### ISSUE TITLE
2.14.2 new errors

### ISSUE THREAD

**Issue by XhmikosR** [JustinBeckwith/linkinator#337]
Hey, @JustinBeckwith. It seems there's a regression, possibly after the htmlparser2 switch:

https://github.com/twbs/bootstrap/pull/35108/checks?check_run_id=3801329205#step:6:34

2.14.0 works without errors.

PS. IMHO the htmlparser2 switch should have been a minor version bump.

**Comment by bcoe** [comment]
sorry for the regression, fixed [here](https://github.com/JustinBeckwith/linkinator/pull/342) and tested against bootstrap.

**Comment by XhmikosR** [comment]
Thanks for the quick fix, and don't mention it, shit break all the time 🙂
