### ISSUE TITLE
Trailing whitespaces causes 404

### ISSUE THREAD

**Issue by fhinkel** [JustinBeckwith/linkinator#348]
TSDoc Syntax recommends a whitespace between link and link text, see https://tsdoc.org/pages/tags/link/. 

Linkinator errors out on those links, e.g., 

```
@see {@link https://cloud.google.com/datastore/docs/concepts/transactions | Transactions Reference}
```
```
Error: [404] https://cloud.google.com/datastore/docs/concepts/transactions%20
```
Relevant PR https://github.com/googleapis/nodejs-datastore/pull/882/

**Comment by JustinBeckwith** [comment]
Linkinator only really scans HTML.  This looks like it's content directly in a TypeScript file.  Can you share an example of an HTML page where this is an issue?

**Comment by JustinBeckwith** [comment]
I think that's exactly what's happening.  That extra `%20` is semantically valid for the url, so I don't think that's a thing I would want to try and strip in the link scanner itself.  For example, if you add `%20` to the end of this [url](https://github.com/JustinBeckwith/linkinator/issues/348%20) it will 404 in the browser.
