### ISSUE TITLE
Parallelize http requests

### ISSUE THREAD

**Issue by JustinBeckwith** [JustinBeckwith/linkinator#35]
Today all HTTP requests are executed serially.  Instead - it could speed things up if we executed requests in a concurrent queue. 

Original request: https://github.com/JustinBeckwith/linkinator/issues/32

**Comment by breck7** [comment]
This would be great. It's very slow right now.

**Comment by breck7** [comment]
If you had this, it seems like it could speed things up 10x, and I'd recommend it to everyone.

Please don't make me read the code and actually contribute myself. 😉

**Comment by breck7** [comment]
Though I do have to say it is very clean code, now that I take a look.
