### ISSUE TITLE
False positive with `https://support.google.com/cloud/answer/6293499`

### ISSUE THREAD

**Issue by tmatsuo** [JustinBeckwith/linkinator#356]
The failure build:
https://github.com/googleapis/nodejs-dialogflow/pull/899

It says:
```
Error: Detected 1 broken links.
 docs/
   [404] https://support.google.com/cloud/answer/6293499
```

The URL works when manually visiting with a browser.

**Comment by tmatsuo** [comment]
I don't know what's happening, but now it's passing.

**Comment by JustinBeckwith** [comment]
Yeah I did a little digging here, and it all passed locally.  I went to re-run the action, and noticed it was green now 🤔  I suspect there is an actual problem with cloudsite.
