### ISSUE TITLE
linkinator-action thinks a link is broken that is not

### ISSUE THREAD

**Issue by sofisl** [JustinBeckwith/linkinator#364]
linkinator action thinks there is a broken link here: (https://github.com/googleapis/nodejs-ai-platform/runs/4413707887?check_suite_focus=true)

https://cloud.google.com/billing/docs/how-to/modify-project?visit_id=637741710275959189-2484501027&rd=1

But this link is working!

**Comment by sofisl** [comment]
Same problem here: https://github.com/googleapis/nodejs-ai-platform/runs/4401422439?check_suite_focus=true

**Comment by JustinBeckwith** [comment]
This is a case of support.google.com having some really questionable behavior.  If you do an HTTP HEAD request, you get a 404:

```
$ curl -I https://support.google.com/cloud/answer/6293499               
HTTP/2 404 
```

If you do an HTTP GET request, you get a 302:
```
$ curl -v https://support.google.com/cloud/answer/6293499
< HTTP/2 301 
< location: https://cloud.google.com/billing/docs/how-to/modify-project?visit_id=637753128253777764-1335583346&rd=1
```

That is a badly behaving web server.

**Comment by JustinBeckwith** [comment]
The good news here is that when you request the doc using a GET, it tells you there was a 302, and that the new url is https://cloud.google.com/billing/docs/how-to/modify-project?visit_id=637875742039315878-2420129944&amp;rd=1.  Given that this is a case of a badly behaving webserver (responding with a 404 for a HEAD request), I am closing this one out as won't fix.
