### ISSUE TITLE
Link is passing but is broken

### ISSUE THREAD

**Issue by tbradbury** [JustinBeckwith/linkinator#388]
We have a link that is broken on our site. It was missing a forward slash `href="some/page"` if you open it in a new tab it works but if you click on it in current tab it goes to a 404 page. 

The solution was to add a slash `href="/some/page"` but we don't know how many other link are also like this. 

We are using next.js for the site

**Comment by JustinBeckwith** [comment]
Greetings!  Could I trouble you for a small repro?  Including a specific page I can scan, or detailed reproduction steps would be super helpful 🤗
