### ISSUE TITLE
Allow checking a single URL (without scanning the page)

### ISSUE THREAD

**Issue by DamianGlowala** [JustinBeckwith/linkinator#502]
Would it be possible to support functionality similar to the following library ([https://github.com/tcort/link-check](https://github.com/tcort/link-check))?

That is, simply checking whether URL is valid or dead, without interacting with the site.

**Comment by JustinBeckwith** [comment]
Greetings!  Looking at link-check, they have a lot of great ideas, and a tool that's a little more specialized for this specific task.  I'd be worried I'm stretching linkinator a bit past what I intended it to do, and it would be hard to actually do this well.  I'm curious - why not just use link-check?
