### ISSUE TITLE
Support for config in JS

### ISSUE THREAD

**Issue by anshulsahni** [JustinBeckwith/linkinator#504]
Recently I was using config file and was trying to use `urlRewriteExperssion` options by specifying regex, JSON doesn't accept all the regex parameters in the text JSON invalidates the string having escape characters which are not known to it. This basically fails to import the config file from NodeJS.

If there is support `linkinator.config.js` then the following benefits can be derived

1. users can do the minor computation for options based on certain factors like environment, etc.
2. specifying params would be much easier as issues with JSON of limited data types will not be there anymore
3. we can have type check on parameters using typescript

@JustinBeckwith Please share your thoughts on having this support, I'm ready to file the PR if you're ready to support this feature

**Comment by JustinBeckwith** [comment]
Hey @anshulsahni that sounds great!  Would love to review a PR.  Could you share the Regex you're trying to use?  I'd like to play around with it to see if I can address the issues with JSON specifically.

**Comment by anshulsahni** [comment]
So I wanted to run a search for a pattern including metacharacter `\w` and while mentioning the regex pattern as a string, the JSON validator gives the error that \w is not a valid escape character in string. Eg: `"urlRewriteSearch": "\w/docs\/"` else if I enter it as a n original RegEx pattern that's off course not valid format for JSON format

**Comment by anshulsahni** [comment]
Also, will file a PR for this feature in the coming days
