### ISSUE TITLE
False positives with v1.10.1?

### ISSUE THREAD

**Issue by julien-deramond** [JustinBeckwith/linkinator#511]
Since few hours we observe errors with `Run JustinBeckwith/linkinator-action@v1`. Maybe that come from the new v1.10.1 release.
Nothing changed on our side, the error began to appear after having rebased some of our PRs.

Example of errors in https://github.com/twbs/bootstrap/runs/7268820877?check_suite_focus=true.

In order to have more details, I have enabled `verbosity: debug` in my fork and created a fake PR. The result with more details can be found in https://github.com/julien-deramond/bootstrap/runs/7269113811?check_suite_focus=true.

If we consider those two errors:
```
Error: [404] _site/docs/5.2/assets/img/bootstrap-icons.png,
Error: [404] _site/docs/5.2/assets/img/bootstrap-themes.png,
```
When launching the corresponding website locally, all the images in error exist at those URLs.
When deployed by Netlify (using this `_site` directory) they also exists:
* https://twbs-bootstrap.netlify.app/docs/5.2/assets/img/bootstrap-icons.png
* https://twbs-bootstrap.netlify.app/docs/5.2/assets/img/bootstrap-themes.png

Other images in this same `img` directory (not at the same level) are not detected as 404 errors:
```
[200] _site/docs/5.2/assets/img/favicons/apple-touch-icon.png
[200] _site/docs/5.2/assets/img/favicons/favicon-32x32.png
```

Something seems weird in this extract; the tested URL contains a comma at the end.
```json
[
  {
    "config": {
      "method": "GET",
      "url": "http://localhost:33887/docs/5.2/assets/img/bootstrap-icons.png,",
      "headers": {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
      },
      "responseType": "stream",
      "timeout": 0
    },
    // ...
  }
]
```

Our GitHub workflow: https://github.com/twbs/bootstrap/blob/main/.github/workflows/docs.yml

Seems to be reproductible as well by doing the following:
```
git clone git@github.com:twbs/bootstrap.git
cd bootstrap
npm i
npm run start

## In an other terminal
npx linkinator http://localhost:9001 --verbosity debug
```

There are not much modifications in your repo since the last version except in `src/action.js`. Maybe it comes from some bumped dependencies.

~~I'm still trying to go further in my analysis.~~

**Edit:** By running `npm linkinator@4.0.0 http://localhost:9001 --verbosity debug` I don't see any errors.
So this regression seems to be observed in the new 4.0.1 version (I can move this issue in the [linkinator repo](https://github.com/JustinBeckwith/linkinator) if needed :) ).

Just saying that by reading the code so it is just a hunch, but in https://github.com/JustinBeckwith/linkinator/commit/9a8a83c35182b3cd4daee62a00f156767fe5c6a7 in `src/links.ts` there was a `        .split(',')` that doesn't seem to be there anymore and could maybe explain the presence of comma in some of the 404 URLs :shrug:

**Comment by julien-deramond** [comment]
> Curiosity - have you identified the specific place in your source code where these links are present? Is there a chance those commas actually exist inside of a srcset attribute, and have the comma?

Yep here is the source code for one of the failing example ([direct link](https://github.com/twbs/bootstrap/blob/3eb6265b65621516f0fda4bf8b4cc4e3cd12e33e/site/layouts/partials/home/masthead-followup.html#L307):

```html
<img class="img-fluid mt-3 mx-auto" srcset="/docs/{{ .Site.Params.docs_version }}/assets/img/bootstrap-icons.png,
                                                    /docs/{{ .Site.Params.docs_version }}/assets/img/bootstrap-icons@2x.png 2x"
                                            src="/docs/{{ .Site.Params.docs_version }}/assets/img/bootstrap-icons.png"
                                            alt="Bootstrap Icons" width="700" height="425" loading="lazy">
```

Indeed `srcset` contains 2 URLs separated by a comma.

_Note: Things like `{{ .Site.Params.docs_version }}` are handled by Hugo to retrieve the version._

**Comment by JustinBeckwith** [comment]
lol sure enough:

```
> value = `/docs/1/assets/img/bootstrap-icons.png,
...                                                     /docs/1/assets/img/bootstrap-icons@2x.png 2x
...                                             `
'/docs/1/assets/img/bootstrap-icons.png,\n' +
  '                                                    /docs/1/assets/img/bootstrap-icons@2x.png 2x\n' +
  '                                            '
> srcset.parseSrcset(value)
[ { url: '/docs/1/assets/img/bootstrap-icons.png,', density: 2 } ]
> 
```

Look at that beautiful trailing comma.  I need to see if there's any manipulation I can safely do here, or if I need to pass this bug up the stack to https://github.com/sindresorhus/srcset.

**Comment by julien-deramond** [comment]
Thanks a lot @JustinBeckwith for this quick weekend patch <3
Don't hesitate if you need some tests from us when `srcset` will provide a patch as well.
Do you plan a new patch release for `linkinator-action` to bump the `linkinator` version?

**Comment by JustinBeckwith** [comment]
No worries at all - I hate it when I break one thing while trying to fix another in a patch release.  I just cut a new release of the action - let me know if you run into any other issues!
