### ISSUE TITLE
Is there a way to see the page broken links exist on?

### ISSUE THREAD

**Issue by jordanlambrecht** [JustinBeckwith/linkinator#513]

**Comment by ManuelRauber** [comment]
If you use the API, there is a `link.parent` property.

**Comment by MattDodsonEnglish** [comment]
You can also see the parent if you use `--format CSV` OR `--format JSON`.

**Comment by JustinBeckwith** [comment]
When you run `linkinator` it starts by streaming the results all as one list of links, but generates a report at the end that shows a per-page breakdown.  As mentioned above, you can also export to JSON or CSV to get it natively in that format.
