### ISSUE TITLE
Request: Allow Passing Custom User-Agent Through Config

### ISSUE THREAD

**Issue by andersoonluan** [JustinBeckwith/linkinator#574]
I'd like the ability to pass my own user-agent string through the configuration settings. This would provide greater flexibility for users who need to set specific user-agent strings for their requests.

Currently user agent is defined here https://github.com/JustinBeckwith/linkinator/blob/a530c40ef717a1d8f7f34f21a4464d4a3206dcd3/src/index.ts#L63 but in some scenarios I'd prefer to pass my own user agent for internal purposes. 

Do we have this possibility today? Are you OK if I open a PR contributing with this functionality? 

Thank you!

**Comment by JustinBeckwith** [comment]
Enjoy :)
