### ISSUE TITLE
Modules not found error 

### ISSUE THREAD

**Issue by alirazaghouri** [JustinBeckwith/linkinator#597]
I just installed 

`npm install linkinator` and getting following error when using 

- Uncaught Error: Module not found: Can't resolve 'net'
- Module not found: Can't resolve 'net'
- Module not found: Can't resolve `'tls'`
- Module not found: Can't resolve 'fs'

...

I have latest node js version

**Comment by JustinBeckwith** [comment]
That's weird!  Usually you will get errors like this if you're trying to use this module in a project that doesn't natively support node.  It's possible you have webpack, angular, or something else set up that's trying to transpile the module to work on the browser, which 1000% ain't going to work.  There are some ideas on how to disable that here:
https://stackoverflow.com/questions/57161839/module-not-found-error-cant-resolve-fs-error
