### ISSUE TITLE
Doesn't find config file if no flags are passed

### ISSUE THREAD

**Issue by karlbrown-va** [JustinBeckwith/linkinator#600]
Linkinator 6.0.4 doesn't find my config file. It's in the current working directory at the top of my source tree. It does work if I pass with `--config` option.

I think it's due to these lines in config.ts
```
	if (flags.config) {
		config = await parseConfigFile(configPath);
	}
```
as such it will only read the config file if flags are passed in.

**Comment by JustinBeckwith** [comment]
Yup, that is totally busted 😆  Fix incomin.
