### ISSUE TITLE
Check #hash anchor links?

### ISSUE THREAD

**Issue by JuroUhlar** [JustinBeckwith/linkinator#601]
Hi, this looks great! 

Have you considered adding an option to check links with hashes? For `https://github.com/JustinBeckwith/linkinator#installation` it would check if there actually is an element with id `installation` present on the page. This would be super useful for my use case. 
Are you open to PRs? 

Thanks!

**Comment by JustinBeckwith** [comment]
Hello!  That's currently tracked in https://github.com/JustinBeckwith/linkinator/issues/79.  Something I'm happy to look at a PR for if someone is interested 🎉
