### ISSUE TITLE
URL encode URLs

### ISSUE THREAD

**Issue by Zach-Durable** [JustinBeckwith/linkinator#632]
URLs like `https://www.glassdoor.com/Salaries/freelance-graphic-designer-salary-SRCH_KO0,26.htm` break the csv output.

I think it'd be sensible to store them as url encoded instead, like https%3A%2F%2Fwww.glassdoor.com%2FSalaries%2Ffreelance-graphic-designer-salary-SRCH_KO0%2C26.htm

**Comment by JustinBeckwith** [comment]
Huh - can you give me an example with complete output?  If I run this:

```
npx linkinator https://www.glassdoor.com/Salaries/freelance-graphic-designer-salary-SRCH_KO0,26.htm --format CSV
```

I end up with this csv:

```csv
url,status,state,parent,failureDetails
"https://www.glassdoor.com/Salaries/freelance-graphic-designer-salary-SRCH_KO0,26.htm",403,BROKEN,"",""
```

Which I _think_ is valid because of the way quotes are wrapped around the url.  Can you give me a bit more - exactly what ain't working?

**Comment by Zach-Durable** [comment]
Yes— I was reading the csv incorrectly.  The quotes solve the issue if you read with pandas or something else like that.
