### ISSUE TITLE
Only limited linked check by api.js code

### ISSUE THREAD

**Issue by alihasan01** [JustinBeckwith/linkinator#68]
I have used code of api.js but it only scan few files from my html pages and showed: 
Scanned total of 100 links!
Detected 16 broken links.

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share the HTML you were trying to scan?

**Comment by alihasan01** [comment]
Hi @JustinBeckwith I am writing my own Typescript code where I used your api.js code to find-out the broken links.
I were trying to scan http://builds.bentley.com/prgbuilds/AzureBuilds/iModelJsDocs/public/ recursively.

**Comment by JustinBeckwith** [comment]
Thanks!  Thank link doesn't seem to work for me (is it authenticated?).  Would you mind creating a minimal github repository with the files?

**Comment by alihasan01** [comment]
https://github.com/alihasan01/Files
Please check the files I have created repository for this.

**Comment by JustinBeckwith** [comment]
So I was able to take a look here.  Sadly - I am getting a bunch of timeouts for links to http://builds.bentley.com:
![image](https://user-images.githubusercontent.com/534619/59161172-1d20ea00-8a94-11e9-9759-adf73cef0efd.png)

This would be a lot easier if there were a public endpoint I could hit :)  One thing to consider - by default linkinator does a shallow scan.  Have you tried passing `--recurse`?
