### ISSUE TITLE
Support link checking of Markdown files

### ISSUE THREAD

**Issue by bnb** [JustinBeckwith/linkinator#73]
Currently 404s and exits on a fresh clone of [one of my repos](https://github.com/bnb/jsconf-eu-led).

Steps:
```
git clone git@github.com:bnb/jsconf-eu-led.git # will clone into jsconf-eu-led
npx linkinator ./jsconf-eu-led # should run against jsconf-eu-led
```

![image](https://user-images.githubusercontent.com/502396/59161836-8402cb00-8ab5-11e9-815e-29595f1055a5.png)

While testing this, it seems that I discovered the localhost URL's port is dynamic rather than static. I'm... not sure why that would happen, considering the code inside the directory is static and not changing between runs:

![image](https://user-images.githubusercontent.com/502396/59161888-46527200-8ab6-11e9-9877-9b9e71d2a97a.png)

**Comment by bnb** [comment]
And, for what it's worth, there doesn't seem to be any reference to localhost in the directory:

![image](https://user-images.githubusercontent.com/502396/59161922-bd880600-8ab6-11e9-8472-9dc7a42db636.png)

**Comment by JustinBeckwith** [comment]
Ok - I know what's happening here :) `linkinator` is expecting you to pass it a path to a *static* HTML site when you use a local path.  It tries to start its own static web server, on a random port, and then navigate the site.  

It can also be pointed at a plain ol' URL.

It sounds like you were expecting this to 404 check your README.md - is that correct?

**Comment by bnb** [comment]
Yup, I was expecting it to check the README.md / other Markdown files in the directory 😅

**Comment by JustinBeckwith** [comment]
That's not an unreasonable expectation.  Let me look at trying to support it!

**Comment by grumbaut** [comment]
I'm getting a similar error as part of our pipeline. We build to HTML files that are used on a local development server. I'm trying to include linkinator as part of our gulp pipeline, but I sometimes get this as the only result:
![Screen Shot 2019-07-09 at 11 59 31 AM](https://user-images.githubusercontent.com/15706633/60904903-ea5c4400-a241-11e9-8945-0378b9ba9d76.png)

Here are the relevant portions of code:
```
	linkChecker.on('pagestart', (fileUrl) => {
		currentFile = sanitizeUrl(fileUrl);
	});

	linkChecker.on('link', (result) => {
		console.log(result);
		// if (result.state === 'BROKEN') {
		// 	const url = result.url.includes('localhost')
		// 		? sanitizeUrl(result.url)
		// 		: result.url;
		// 	this.log('linkCheck', `Broken link in ${currentFile}: ${url}`, 'red');
		// }
	});

	const task = () => linkChecker.check({
		path: path.resolve(this.epubDir),
		recurse: true,
	});
```

**Comment by JustinBeckwith** [comment]
👋 @grumbaut it sounds like your issue may be different, since you're working from generated HTML instead of Markdown (the original issue with this one).  Could I trouble you to open a new issue?

**Comment by grumbaut** [comment]
Done! Thanks!

**Comment by bnb** [comment]
I just ran into this again thinking it was supported and remembered I'd had an issue previously 😅

**Comment by JustinBeckwith** [comment]
Well it took longer than expected, but I finally got around to this 🐢   With version `2.6.0` and up, you can now check markdown!  

```
$ linkinator README.md
```

That ought to do it!  Anyone want to take this for a spin and let me know how it goes?
