### ISSUE TITLE
Add support for XHTML files?

### ISSUE THREAD

**Issue by grumbaut** [JustinBeckwith/linkinator#76]
We're hoping to use linkinator as part of our ebook development pipeline to check for dead links in XHTML files. When we run linkinator in our build directory, though, we don't get any results.

Is there any interest in/work being on supporting XHTML files?

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  If it's not a ton of extra code, I'm not opposed to adding support.  If I had to guess, I'd assume the default index page when we stand up the little fake web server would be the first thing to check :)

**Comment by grumbaut** [comment]
Sorry for the delay! I'm just circling back to this.

I addressed this in #93. The change was actually pretty easy--we just need to check for `application/xhtml+xml` in the `isHTML` function.

**Comment by grumbaut** [comment]
Thanks for merging so quickly, @JustinBeckwith! I appreciate it. Would it be possible to do this as a release to NPM so I can add this to my project (whenever you have a chance)? Thanks again!

**Comment by JustinBeckwith** [comment]
Absolutely!  It's supposed to happen automatically, but there was a CI bug :) Cutting the release now!  It should leave a comment in #93 when it goes out.

**Comment by grumbaut** [comment]
Thanks!
