### ISSUE TITLE
404 on Local Host URL When Checking Local HTML Files

### ISSUE THREAD

**Issue by grumbaut** [JustinBeckwith/linkinator#77]
I'd love to use linkinator as part of our development pipeline. We build to HTML files that are used on a local development server. I'm trying to include linkinator as part of our gulp tasks
, but I sometimes get this as the only result:
![Screen Shot 2019-07-09 at 11 59 31 AM](https://user-images.githubusercontent.com/15706633/60906226-ab7bbd80-a244-11e9-9612-fdb023a6ee0b.png)

Here are the relevant portions of code:
```js
linkChecker.on('pagestart', (fileUrl) => {
  currentFile = sanitizeUrl(fileUrl);
});

linkChecker.on('link', (result) => {
  console.log(result);
});

const task = () => linkChecker.check({
  path: path.resolve(this.epubDir), // this.epubDir is pointing to a local directory
  recurse: true,
});
```

**Comment by grumbaut** [comment]
I'm not sure if this is an issue with my implementation or an issue with linkinator itself.

**Comment by lrobledo** [comment]
@grumbaut 
I was having the same issue, but I was using the CLI.

I was originally running `linkinator dist/index.html` and getting a 404 error.
When I changed it to `linkinator dist/` it checked the links in `index.html` and didn't error out.

Perhaps your problem is related?

**Comment by grumbaut** [comment]
Ah! This sounds like it might be the problem. I believe I'm passing it individual files rather than the directory. I'll try this out and post an update soon. Thanks!

**Comment by grumbaut** [comment]
@lrobledo, I think this was my problem. Thanks!
