### ISSUE TITLE
Consider exposing request failure error details

### ISSUE THREAD

**Issue by ashur** [JustinBeckwith/linkinator#78]
## Configuration

* **Version** — 1.5.0

## Steps

1. Run linkinator against a URL which will produce some kind of request error — ex., a domain with an SSL certificate issue:

```
npx linkinator https://example.com.s3.amazonaws.com
```

(Alternatively, run linkinator against a page which links to a URL that will produce the error.)

## Current Behavior

This is currently reported with error status `0`, and no additional details:

```
$ npx linkinator https://example.com.s3.amazonaws.com
🏊‍♂️ crawling https://example.com.s3.amazonaws.com
  [0] https://example.com.s3.amazonaws.com


ERROR: Detected 1 broken links. Scanned 1 links in 0.294 seconds.
```

## Desired Behavior

It would be helpful, especially in cases where the request error uncovers a previously unknown issue at the URL in question, if any additional information about the request failure could be included in the summary.

(It could be outside the scope of the tool to report information beyond HTTP status code, which I would certainly understand.)

Thanks!

## Severity

* Enhancement

**Comment by JustinBeckwith** [comment]
So good news - this just went out in https://github.com/JustinBeckwith/linkinator/releases/tag/v2.10.0!  To get the full error details from the request:

```
$ linkinator your-site --verbosity DEBUG
```

Hope this helps!
