### ISSUE TITLE
Empty href isn't detected as broken

### ISSUE THREAD

**Issue by XhmikosR** [JustinBeckwith/linkinator#80]
I noticed this by accident. We had (still have at the time of writing this) a link on our docs that does nothing:

```html
<a href="" class="text-muted">Previous releases</a> 
```

Wouldn't it make sense to catch this case?

Thanks!

**Comment by XhmikosR** [comment]
BTW this seems to be valid HTML, and the link just goes to the page itself. I can't think of any reason one would use this on purpose, but maybe I'm missing something.

**Comment by JustinBeckwith** [comment]
I think this one is working as intended.  This is pretty much the same as not including an `href` tag at all, which is useful for things like `<a name>`, and a variety of other things I could never really predict :) I am going to leave this one as is for now.
